const GET_INITIAL_REQUEST = 'GET_INITIAL_REQUEST';
const GET_INITIAL_REQUEST_COMPLETE = 'GET_INITIAL_REQUEST_COMPLETE';
const GET_INITIAL_REQUEST_FAILED = 'GET_INITIAL_REQUEST_FAILED';

export {GET_INITIAL_REQUEST}
export {GET_INITIAL_REQUEST_COMPLETE}
export {GET_INITIAL_REQUEST_FAILED}